# roles/oioswift/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_oioswift_namespace }}"
    - path: "{{ openio_oioswift_sysconfig_dir }}/{{ openio_oioswift_servicename }}"
    - path: "/etc/swift"
      owner: root
      group: root
    - path: "/var/log/oio/sds/{{ openio_oioswift_namespace }}/{{ openio_oioswift_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
    backup: "{{ openio_oioswift_backup_file_modifications }}"
  with_items:
    - src: "proxy-server.conf.j2"
      dest: "{{ openio_oioswift_sysconfig_dir }}/\
        {{ openio_oioswift_servicename }}/proxy-server.conf"
    - src: "gridinit_oioswift.conf.j2"
      dest: "{{ openio_oioswift_gridinit_dir }}/{{ openio_oioswift_gridinit_file_prefix }}\
        {{ openio_oioswift_servicename }}.conf"
    - src: "swift.conf.j2"
      dest: "/etc/swift/swift.conf"
  register: _oioswift_conf

- name: restart oioswift
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{ openio_oioswift_namespace }}-{{ openio_oioswift_servicename }}
  tags: configure
  when:
    - _oioswift_conf.changed
    - not openio_oioswift_provision_only
...
