# roles/oioswift/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - install
    - configure

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Install oioswift extended
  package:
    name: openio-sds-swift-extended
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_oioswift_extended
  until: install_oioswift_extended is success
  retries: 5
  delay: 2
  tags: install
  when: openio_oioswift_extended

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_oioswift_namespace }}"
    - path: "{{ openio_oioswift_sysconfig_dir }}/{{ openio_oioswift_servicename }}"
    - path: "/etc/swift"
      owner: root
      group: root
    - path: "{{ openio_oioswift_sysconfig_dir }}/watch"
    - path: "/var/log/oio/sds/{{ openio_oioswift_namespace }}/{{ openio_oioswift_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: configure

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
    backup: "{{ openio_oioswift_backup_file_modifications }}"
  with_items:
    - src: "proxy-server.conf.j2"
      dest: "{{ openio_oioswift_sysconfig_dir }}/\
        {{ openio_oioswift_servicename }}/proxy-server.conf"
    - src: "gridinit_oioswift.conf.j2"
      dest: "{{ openio_oioswift_gridinit_dir }}/{{ openio_oioswift_gridinit_file_prefix }}\
        {{ openio_oioswift_servicename }}.conf"
    - src: "swift.conf.j2"
      dest: "/etc/swift/swift.conf"
    - src: "watch-oioswift.yml.j2"
      dest: "{{ openio_oioswift_sysconfig_dir }}/watch/{{ openio_oioswift_servicename }}.yml"
  register: _oioswift_conf
  tags: configure

- name: Generate IAM policies
  template:
    src: iam_rules.json.j2
    dest: "{{ openio_oioswift_sysconfig_dir }}/\
      {{ openio_oioswift_servicename }}/iam_rules.json"
    owner: openio
    group: openio
    mode: 0640
    backup: "{{ openio_oioswift_backup_file_modifications }}"
  register: _iam_conf
  tags: configure
  when:
    - not openio_oioswift_extended
    - "'iam' in openio_oioswift_pipeline"

- name: "restart oioswift to apply the new configuration"
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{ openio_oioswift_namespace }}-{{ openio_oioswift_servicename }}
  tags: configure
  register: _restart_oioswift
  when:
    - _oioswift_conf is changed or _iam_conf is changed
    - not openio_oioswift_provision_only

- block:
    - name: "Ensure oioswift is started"
      command: gridinit_cmd start {{ openio_oioswift_namespace }}-{{ openio_oioswift_servicename }}
      register: _start_oioswift
      changed_when: '"Success" in _start_oioswift.stdout'
      when:
        - not openio_oioswift_provision_only
        - _restart_oioswift is skipped
      tags: configure

    - name: check oioswift
      uri:
        url: "http://{{ openio_oioswift_bind_address }}:{{ openio_oioswift_bind_port }}/healthcheck"
        return_content: true
        status_code: 200
      register: _oioswift_check
      retries: 3
      delay: 5
      until: _oioswift_check is success
      changed_when: false
      tags: configure
      when:
        - not openio_oioswift_provision_only
  when: openio_bootstrap | d(false)
...
